site_name: Arif Yahya Public Pages
site_url: https://arif-yahya.github.io/public/
theme:
  name: material
  features:
    - navigation.tracking
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    #- navigation.tabs.sticky
    - navigation.sections
    - navigation.path
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: teal
      accent: lime

plugins:
  - search
  - blog

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/arif-yahya
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/#
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/#

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

copyright: |
  &copy; 2024 <a href="https://github.com/arif-yahya"  target="_blank" rel="noopener">Arif Yahya</a>
